/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Chris' at '19/11/16 14:56' with Gradle 3.2
 *
 * @author Chris, @date 19/11/16 14:56
 */
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;
import org.jsoup.nodes.Document;
 
public class OWA {

  protected String readFile(String filename)
  {
    String content = null;
    File file = new File(filename);
    FileReader reader = null;
    try {
      reader = new FileReader(file);
      char[] chars = new char[(int) file.length()];
      reader.read(chars);
      content = new String(chars);
      reader.close();
    } catch (IOException e) {
      e.printStackTrace();
    } finally {
      try {
        if(reader !=null){reader.close();}
      } catch (IOException e) {
        e.printStackTrace();
      }
    }
    return content;
  }

  protected Date parseDate(String string) {
    Date result = new Date();
    DateFormat format = new SimpleDateFormat("M/d/y h:m a");
    try {
      result = format.parse(string);
    } catch (ParseException e) {
      e.printStackTrace();
    }
    return result;
  }

  protected ArrayList<Map> parseList(String html) {
    ArrayList<Map> results = new ArrayList<Map>();
    Document doc = Jsoup.parse(html);
    Elements rows = doc.select("div.cntnt table tr:gt(2)");
    for (Element row: rows) {
      Elements cols = row.select("td");
      Map result = new HashMap();
      result.put("id", cols.eq(3).select("input").attr("value"));
      result.put("name", cols.eq(4).text());
      result.put("subject", cols.eq(5).text());
      result.put("date", parseDate(cols.eq(6).text()));
      result.put("size", cols.eq(7).text());
      results.add(result);
    }
    return results;
  }

  protected Map parseEmail (String html) {
    Document doc = Jsoup.parse(html);
    Map result = new HashMap();
    ArrayList<String> toArray = new ArrayList<String>();
    ArrayList<String> ccArray = new ArrayList<String>();

    result.put("subject", doc.select("td.sub").text());
    result.put("from", doc.select("td.frm").text());
    result.put("date", doc.select("td.hdtxnr:eq(0)").text());
    Elements toList = doc.select("#divTo a");
    for (Element toItem: toList) {
      toArray.add(toItem.text());
    }
    Elements ccList = doc.select("#divCc a");
    for (Element ccItem: ccList) {
      ccArray.add(ccItem.text());
    }
    result.put("to", toArray);
    result.put("cc", ccArray);
    return result;
  }

  protected ArrayList<String> parseRecentRecipients(String html) {
    Document doc = Jsoup.parse(html);
    ArrayList<String> emails = new ArrayList<String>(); 
    Elements rows = doc.select("#selmrr option");
    for (Element row: rows) {
      emails.add(row.text()+" <"+row.attr("title")+">");
    }
    return emails;
  }

  public static void main(String[] args) {
    OWA owa = new OWA();
    System.out.println(owa.parseRecentRecipients(owa.readFile(args[0])));
  }
}
