import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'Chris' at '19/11/16 14:56' with Gradle 3.2
 *
 * @author Chris, @date 19/11/16 14:56
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        //Library classUnderTest = new Library();
        //assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
